# -*- coding: utf-8 -*-
"""Burgers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RNjWrtDbkAJdUe2-_ltKI3PHkSmrDaxS
"""

import torch
import torch.nn as nn
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.gridspec import GridSpec

# Set random seeds for reproducibility
torch.manual_seed(123)
np.random.seed(123)

class FCN(nn.Module):
    """
    Standard Fully Connected Network for PINNs
    """
    def __init__(self, N_INPUT=2, N_OUTPUT=1, N_HIDDEN=20, N_LAYERS=8):
        super().__init__()
        activation = nn.Tanh
        self.fcs = nn.Sequential(*[nn.Linear(N_INPUT, N_HIDDEN), activation()])
        self.fch = nn.Sequential(*[
                        nn.Sequential(*[nn.Linear(N_HIDDEN, N_HIDDEN), activation()])
                        for _ in range(N_LAYERS-1)])
        self.fce = nn.Linear(N_HIDDEN, N_OUTPUT)

    def forward(self, x):
        x = self.fcs(x)
        x = self.fch(x)
        x = self.fce(x)
        return x

if __name__ == '__main__':
    """
    Train the physics-informed neural network (PINN) model for Burgers' equation in PyTorch
    """
    print("Generating data...")
    num_train_samples = 10000
    num_test_samples = 1000
    nu = 0.01 / np.pi  # Kinematic viscosity

    # --- 1. Generate Training Data ---
    # Equation Collocation Points
    t_eqn_np = np.random.rand(num_train_samples, 1)        # t = 0 ~ +1
    x_eqn_np = 2 * np.random.rand(num_train_samples, 1) - 1  # x = -1 ~ +1

    # Initial Condition Points (t=0)
    tx_ini = 2 * np.random.rand(num_train_samples, 2) - 1
    tx_ini[..., 0] = 0
    u_ini = -np.sin(np.pi * tx_ini[..., 1, np.newaxis])

    # Boundary Condition Points (x=-1 or x=+1)
    tx_bnd = np.random.rand(num_train_samples, 2)
    tx_bnd[..., 1] = 2 * np.round(tx_bnd[..., 1]) - 1
    u_bnd = np.zeros((num_train_samples, 1))

    # Convert to PyTorch Tensors
    # We keep t and x separate for the equation points to make autograd cleaner
    t_eqn = torch.tensor(t_eqn_np, dtype=torch.float32, requires_grad=True)
    x_eqn = torch.tensor(x_eqn_np, dtype=torch.float32, requires_grad=True)

    tx_ini_tensor = torch.tensor(tx_ini, dtype=torch.float32)
    u_ini_tensor = torch.tensor(u_ini, dtype=torch.float32)

    tx_bnd_tensor = torch.tensor(tx_bnd, dtype=torch.float32)
    u_bnd_tensor = torch.tensor(u_bnd, dtype=torch.float32)

    # --- 2. Initialize Model & Optimizer ---
    # 2 inputs (t, x), 1 output (u), 8 hidden layers with 20 neurons each
    model = FCN(2, 1, 20, 8)

    # PyTorch's L-BFGS implementation
    optimizer = torch.optim.LBFGS(
        model.parameters(),
        lr=1.0,
        max_iter=5000,
        max_eval=5000,
        tolerance_grad=1e-5,
        tolerance_change=1e-9,
        history_size=50,
        line_search_fn="strong_wolfe"
    )

    # --- 3. Training Loop (Closure Function) ---
    def closure():
        optimizer.zero_grad()

        # A. Physics Loss (Burgers' Equation: u_t + u*u_x - nu*u_xx = 0)
        tx_stacked = torch.cat([t_eqn, x_eqn], dim=1)
        u = model(tx_stacked)

        # Calculate derivatives using autograd
        u_t = torch.autograd.grad(u, t_eqn, grad_outputs=torch.ones_like(u), create_graph=True)[0]
        u_x = torch.autograd.grad(u, x_eqn, grad_outputs=torch.ones_like(u), create_graph=True)[0]
        u_xx = torch.autograd.grad(u_x, x_eqn, grad_outputs=torch.ones_like(u_x), create_graph=True)[0]

        physics_residual = u_t + u * u_x - nu * u_xx
        loss_physics = torch.mean(physics_residual ** 2)

        # B. Initial Condition Loss
        u_ini_pred = model(tx_ini_tensor)
        loss_ini = torch.mean((u_ini_pred - u_ini_tensor) ** 2)

        # C. Boundary Condition Loss
        u_bnd_pred = model(tx_bnd_tensor)
        loss_bnd = torch.mean((u_bnd_pred - u_bnd_tensor) ** 2)

        # Total Loss
        loss = loss_physics + loss_ini + loss_bnd
        loss.backward()
        return loss

    print("Training model (this may take a few minutes)...")
    optimizer.step(closure)

    # Final loss check
    final_loss = closure()
    print(f"Training finished. Final Loss: {final_loss.item():.6f}")

    # --- 4. Export for GIIT Engine ---
    torch.save(model.state_dict(), 'burgers_1d.pt')
    print("Model successfully exported as 'burgers_1d.pt'")

    # --- 5. Prediction & Plotting ---
    print("Generating plots...")
    t_flat = np.linspace(0, 1, num_test_samples)
    x_flat = np.linspace(-1, 1, num_test_samples)
    t, x = np.meshgrid(t_flat, x_flat)
    tx = np.stack([t.flatten(), x.flatten()], axis=-1)

    # Predict with PyTorch
    with torch.no_grad():
        tx_tensor = torch.tensor(tx, dtype=torch.float32)
        u_pred = model(tx_tensor).numpy()

    u = u_pred.reshape(t.shape)

    # Visualization
    fig = plt.figure(figsize=(7, 4))
    gs = GridSpec(2, 3)

    plt.subplot(gs[0, :])
    plt.pcolormesh(t, x, u, cmap='rainbow', shading='auto')
    plt.xlabel('t')
    plt.ylabel('x')
    cbar = plt.colorbar(pad=0.05, aspect=10)
    cbar.set_label('u(t,x)')
    cbar.mappable.set_clim(-1, 1)

    t_cross_sections = [0.25, 0.5, 0.75]
    for i, t_cs in enumerate(t_cross_sections):
        plt.subplot(gs[1, i])
        tx_cs = np.stack([np.full(t_flat.shape, t_cs), x_flat], axis=-1)
        with torch.no_grad():
            tx_cs_tensor = torch.tensor(tx_cs, dtype=torch.float32)
            u_cs = model(tx_cs_tensor).numpy()

        plt.plot(x_flat, u_cs)
        plt.title(f't={t_cs}')
        plt.xlabel('x')
        plt.ylabel('u(t,x)')
        plt.ylim(-1.2, 1.2)

    plt.tight_layout()
    plt.show()